# netlify.toml

[build]
  # If you have a frontend to build, set your command and publish directory here.
  # If it's just a backend, 'npm install' might be enough to get function dependencies.
  command = "npm install" # Assuming you only need to install dependencies for the functions
  publish = "public" # Or whatever folder you use for static assets, or omit if no frontend

[functions]
  directory = "netlify/functions"
  node_version = "20"
  node_bundler = "esbuild" # Recommended for smaller bundle sizes and faster deploys

# Redirect to make your API endpoint clean
[[redirects]]
  from = "/api/graphql"
  to = "/.netlify/functions/graphql" # This targets the 'graphql.js' function
  status = 200 # For proxying
  force = true # Essential for API routes